name: Issue workflow
on: issues
jobs:
  github-info:
    runs-on: ubuntu-22.04
    steps:
    - name: Print github info
      run: |
        echo "User: ${{github.event.issue.user.login}}"
        echo "Title: ${{github.event.issue.title}}"
